# Generated by Django 5.2.3 on 2025-07-01 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_access', models.BooleanField(default=True, verbose_name='دسترسی به سایت')),
            ],
            options={
                'verbose_name': 'Server',
            },
        ),
    ]
