# Generated by Django 5.2.3 on 2025-06-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.URLField(verbose_name='Site domain')),
                ('access_key', models.CharField(max_length=128)),
                ('expire_at', models.DateTimeField(verbose_name='Expire At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('domain_owner', models.CharField(blank=True, max_length=255, null=True, verbose_name='Domain owner name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Started at')),
            ],
            options={
                'verbose_name': 'سایت',
                'verbose_name_plural': 'سایت ها',
            },
        ),
    ]
