# Generated by Django 5.2.3 on 2025-06-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='site',
            options={'verbose_name': 'Website', 'verbose_name_plural': 'Websites'},
        ),
        migrations.AddField(
            model_name='site',
            name='domain_owner_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Domain owner id'),
        ),
    ]
